spring:
  profiles:
    active: dev # dev # test # pro
---
server:
  port: 1106
api: api
open: open
version: V1.0.0
websocket-url: ws://10.16.105.24:8889/webSocket
spring:
  profiles: dev
  data:
    mongodb:
   #   host: 10.16.105.13 # localhost
      host: localhost
      port: 27017
      database: dotayu
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
  application:
    name: onlinecommand-service
  devtools:
    livereload:
      port: 35712
 #thymeleaf start
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
       content-type: text/html
    cache: false
 #thymeleaf end
logging:
config=classpath: logback-test.xm l